name: Push main branch to EC2
on: push
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
        ref: 'main'
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        name: id_rsa
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - run: |
        git remote add ec2 ubuntu@ec2-44-196-226-184.compute-1.amazonaws.com:/var/www/yaml-test/yaml-test.git
        git config --global user.email "yoshizachz@gmail.com"
        git config --global user.name "gh workflow"
        git checkout main
        git push -u ec2 main